---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.envVarsConfigMapName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- range $key, $val := $.Values.extraLabels }}
    {{ $key }}: {{ $val }}
    {{- end }}

data:
  {{- range $key, $val := $.Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
